# Generated by Django 5.1.3 on 2024-11-25 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
