# Generated by Django 5.1.3 on 2024-12-01 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_record_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutant',
            name='tax_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
