# Generated by Django 5.1.3 on 2024-12-01 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pollutant_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='calculated_tax',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='record',
            name='tax_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
