# Generated by Django 5.1.3 on 2024-12-09 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_record_calculated_tax_record_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutant',
            name='cancer_risk_type',
            field=models.CharField(choices=[('cancerogenic', 'Канцерогенний'), ('non_cancerogenic', 'Неканцерогенний')], default='non_cancerogenic', max_length=20),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='rfc',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='RFC середньодобова концентрація'),
        ),
    ]
